plugins {
    id 'java'
    id("com.gradleup.shadow") version "9.3.1"
}

group = 'com.jagrosh'
version = '4.0.0'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven {url = uri("https://m2.chew.pro/releases")}
    maven {url = uri("https://m2.duncte123.dev/releases")}
    maven {url = uri("https://maven.lavalink.dev/releases")}

}

jar {
    manifest {
        attributes(
                'Main-Class': 'com.jagrosh.jmusicbot.JMusicBot'
        )
    }
}

dependencies {
    implementation 'net.dv8tion:JDA:6.3.0'
    implementation 'pw.chew:jda-chewtils:2.2.1'
    implementation 'dev.arbjerg:lavaplayer:2.2.7'
    implementation 'dev.lavalink.youtube:common:1.18.2'
    implementation 'com.github.jagrosh:JLyrics:master-SNAPSHOT'
    implementation 'com.dunctebot:sourcemanagers:1.9.0'
    implementation 'ch.qos.logback:logback-classic:1.2.13'
    implementation 'com.typesafe:config:1.3.2'
    implementation 'org.jsoup:jsoup:1.15.3'

    implementation "club.minnced:jdave-api:0.1.8"
    implementation "club.minnced:jdave-native-linux-x86-64:0.1.8"
    implementation "club.minnced:jdave-native-linux-aarch64:0.1.8"
    implementation "club.minnced:jdave-native-win-x86-64:0.1.8"
    implementation "club.minnced:jdave-native-darwin:0.1.8"

    testImplementation 'junit:junit:4.13.1'
    testImplementation 'org.hamcrest:hamcrest-core:1.3'
}
